### ISSUE TITLE
Add ID metadata field to sections

### ISSUE THREAD

**Issue by angellg1** [hlxsites/graco-mybenefits#41]
Add an ID field to section metadata to enable the use of anchor links within a page.
Example:
<img width="664" alt="image" src="https://user-images.githubusercontent.com/126094642/234355643-9a0da90c-3032-43bd-a1fe-1a78ad7f19ea.png">
<img width="590" alt="image" src="https://user-images.githubusercontent.com/126094642/234355803-5dfc2f65-2d85-4fd4-9245-6af41df51e4f.png">

**Comment by bstopp** [comment]
Though, there appears to be a bug in the translation of the link on the serverside. I am opening a ticket with the Product team to resolve.

**Comment by angellg1** [comment]
Thanks, Bryan! Let me know when the Product team has a fix in so I can retest.

**Comment by bstopp** [comment]
This has been resolved on the Product side. You will need to re-preview/publish the pages that have these types of links.
