### ISSUE TITLE
Center text style should only center text horizontally, not vertically

### ISSUE THREAD

**Issue by angellg1** [hlxsites/graco-mybenefits#43]
When center is applied as a section style, the text should continue to be top positioned vertically, and centered only horizontally.

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/126094642/234384946-59b95f1d-05ed-42b6-9bfb-2096381acd5b.png">

**Comment by bstopp** [comment]
Hm, this may be tricky, but i'll see what i can do.

**Comment by bstopp** [comment]
Let me know if this is what you're looking for:

https://bug-columns-alignment--graco-mybenefits--hlxsites.hlx.page/supplemental

**Comment by angellg1** [comment]
Yes, that's perfect!
